#存基础url、数据库连接信息；
#by:your old brother
#基础url
EnvironMent:
#  Chose: yyy
  Chose: xxx
base_url:
  stg_mer_url: 'xxx'
  stg_ops_url: 'xxx'
  test_ops_url: "xxx"
  test_mer_url: "xxx"
  evd_ops_url: 'xxx'
  evd_mer_url: 'xxx'
  mock_url: 'xx'


#logger信息：
logger:
  name: "LDW"
  level: "INFO"
  format: '[%(asctime)s] %(filename)s->%(funcName)s line:%(lineno)d [%(levelname)s] %(message)s'
#获取token值password

#提取值位数设置,默认取首个值
extract:
  num: 1

#public key
sstoken:
  Authorization:

#new contract
ContainerList:
  containerModel: 20GP
  containerFh: 15413
  containerWeight: 28
  shippingCompany: "船公司"
  fromAddress: "起始地"
  toAddress: "到货地"
  departureTime: "2022-6-9"
  arrivalTime: ""